CREATE TABLE Person (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100),
    BirthDate DATE,
    Sex CHAR(1),
    UNIQUE (Id)
);

CREATE TABLE Committee (
    Id SERIAL PRIMARY KEY REFERENCES PERSON(Id)
	ON DELETE CASCADE ON UPDATE CASCADE,
    Type VARCHAR(100),
    Position VARCHAR(100)
);

CREATE TABLE Referee (
    Id INT PRIMARY KEY REFERENCES Person(Id)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Footballer (
    Id SERIAL PRIMARY KEY REFERENCES Person(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Administrator (
    Id INT PRIMARY KEY REFERENCES Person(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    password_hash VARCHAR(100) NOT NULL,
    PhoneNum VARCHAR(20),
    Email VARCHAR(100),
    Address VARCHAR(255)
);

CREATE TABLE Field (
    Location VARCHAR(100) NOT NULL,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Type VARCHAR(100),
    Capacity INT
);

CREATE TABLE Club (
    Name VARCHAR(100) PRIMARY KEY,
    Email VARCHAR(100),
    Address VARCHAR(255),
	Homeground_field VARCHAR(100) REFERENCES Field(name)
	ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE Match (
    MatchId SERIAL PRIMARY KEY,
    Category VARCHAR(100),
    Season VARCHAR(100),
    Association VARCHAR(100),
	JudgeId INT REFERENCES Referee(Id)
	ON DELETE CASCADE ON UPDATE CASCADE,
	Date DATE,
	Time TIME,
	Field_name VARCHAR(100) REFERENCES Field(Name)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Belongs (
    StartDate DATE NOT NULL,
    LastDate DATE,
    FootballerId INT,
    ClubName VARCHAR(100),
    FOREIGN KEY (FootballerId) REFERENCES Footballer(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ClubName) REFERENCES Club(Name) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE Participates (
    MinutesPlayed INT,
    YellowCard SMALLINT CHECK (YellowCard >= 0 AND YellowCard <= 2),
    RedCard BOOLEAN,
    Goals INT,
    OwnGoals INT,
    FootballerId INT,
    MatchId INT,
	PRIMARY KEY (FootballerId,MatchId),
    FOREIGN KEY (FootballerId) REFERENCES Footballer(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MatchId) REFERENCES Match(MatchId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Play (
    ClubHome VARCHAR(100),
    ClubAway VARCHAR(100),
    FieldName VARCHAR(100),
    MatchId INT,
	PRIMARY KEY(MatchId,FieldName,ClubHome,ClubAway),
    FOREIGN KEY (ClubHome) REFERENCES Club(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ClubAway) REFERENCES Club(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FieldName) REFERENCES Field(Name) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MatchId) REFERENCES Match(MatchId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Announcement (
	Code SERIAL NOT NULL PRIMARY KEY,
	Title VARCHAR(100),
	TextInput VARCHAR(1000),
	DateAnnounced DATE,
	TimeAnnounced TIME,
	AdminId INT REFERENCES Administrator(Id)
	ON DELETE CASCADE ON UPDATE CASCADE
);



