# fly.toml app configuration file generated for project-attempt-main on 2024-05-26T20:30:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-attempt-main'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
